config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/Index'

  resources :status_clients

  resources :clients

  resources :bar_codes

  resources :visits

  resources :municipalities

  resources :states

end

app/models/visit.rb
class Visit < ActiveRecord::Base

	belongs_to :client

end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy]

  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
  end

  # GET /visits/new
  def new
    @visit = Visit.new
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(visit_params)

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Visit was successfully created.' }
        format.json { render :show, status: :created, location: @visit }
      else
        format.html { render :new }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { render :show, status: :ok, location: @visit }
      else
        format.html { render :edit }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit.destroy
    respond_to do |format|
      format.html { redirect_to visits_url, notice: 'Visit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visit_params
      params.require(:visit).permit(:client_id, :employeName, :productsName)
    end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= form_for(@visit) do |f| %>
  <% if @visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% @visit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :client_id %><br>
    <%= f.number_field :client_id %>
  </div>
  <div class="field">
    <%= f.label :employeName %><br>
    <%= f.text_field :employeName %>
  </div>
  <div class="field">
    <%= f.label :productsName %><br>
    <%= f.text_field :productsName %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visits/edit.html.erb
<h1>Editing visit</h1>

<%= render 'form' %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %>

app/views/visits/index.html.erb
<h1>Listing visits</h1>

<table>
  <thead>
    <tr>
      <th>Client_id</th>
      <th>Employename</th>
      <th>Productsname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visits.each do |visit| %>
      <tr>
        <td><%= visit.client_id %></td>
        <td><%= visit.employeName %></td>
        <td><%= visit.productsName %></td>
        <td><%= link_to 'Show', visit %></td>
        <td><%= link_to 'Edit', edit_visit_path(visit) %></td>
        <td><%= link_to 'Destroy', visit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visit', new_visit_path %>

app/views/visits/new.html.erb
<h1>New visit</h1>

<%= render 'form' %>

<%= link_to 'Back', visits_path %>

app/views/visits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Clientid:</strong>
  <%= @visit.client_id %>
</p>

<p>
  <strong>Employename:</strong>
  <%= @visit.employeName %>
</p>

<p>
  <strong>Productsname:</strong>
  <%= @visit.productsName %>
</p>

<%= link_to 'Edit', edit_visit_path(@visit) %> |
<%= link_to 'Back', visits_path %>