config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/Index'

  resources :status_clients

  resources :clients

  resources :bar_codes

  resources :visits

  resources :municipalities

  resources :states

end

app/models/state.rb
class State < ActiveRecord::Base
	has_many :municipalities
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:name)
    end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_form.html.erb
<%= form_for(@state) do |f| %>
  <% if @state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% @state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/states/edit.html.erb
<h1>Editing state</h1>

<%= render 'form' %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<h1>Listing states</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @states.each do |state| %>
      <tr>
        <td><%= state.name %></td>
        <td><%= link_to 'Show', state %></td>
        <td><%= link_to 'Edit', edit_state_path(state) %></td>
        <td><%= link_to 'Destroy', state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New State', new_state_path %>

app/views/states/new.html.erb
<h1>New state</h1>

<%= render 'form' %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @state.name %>
</p>

<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>