config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/Index'

  resources :status_clients

  resources :clients

  resources :bar_codes

  resources :visits

  resources :municipalities

  resources :states

end

app/models/bar_code.rb
class BarCode < ActiveRecord::Base


end

app/controllers/bar_codes_controller.rb
class BarCodesController < ApplicationController
  before_action :set_bar_code, only: [:show, :edit, :update, :destroy]

  # GET /bar_codes
  # GET /bar_codes.json
  def index
    @bar_codes = BarCode.all
  end

  # GET /bar_codes/1
  # GET /bar_codes/1.json
  def show
  end

  # GET /bar_codes/new
  def new
    @bar_code = BarCode.new
  end

  # GET /bar_codes/1/edit
  def edit
  end

  # POST /bar_codes
  # POST /bar_codes.json
  def create
    @bar_code = BarCode.new(bar_code_params)

    respond_to do |format|
      if @bar_code.save
        format.html { redirect_to @bar_code, notice: 'Bar code was successfully created.' }
        format.json { render :show, status: :created, location: @bar_code }
      else
        format.html { render :new }
        format.json { render json: @bar_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bar_codes/1
  # PATCH/PUT /bar_codes/1.json
  def update
    respond_to do |format|
      if @bar_code.update(bar_code_params)
        format.html { redirect_to @bar_code, notice: 'Bar code was successfully updated.' }
        format.json { render :show, status: :ok, location: @bar_code }
      else
        format.html { render :edit }
        format.json { render json: @bar_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bar_codes/1
  # DELETE /bar_codes/1.json
  def destroy
    @bar_code.destroy
    respond_to do |format|
      format.html { redirect_to bar_codes_url, notice: 'Bar code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bar_code
      @bar_code = BarCode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bar_code_params
      params.require(:bar_code).permit(:code, :path)
    end
end

app/helpers/bar_codes_helper.rb
module BarCodesHelper
end

app/views/bar_codes/_form.html.erb
<%= form_for(@bar_code) do |f| %>
  <% if @bar_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bar_code.errors.count, "error") %> prohibited this bar_code from being saved:</h2>

      <ul>
      <% @bar_code.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :path %><br>
    <%= f.text_field :path %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bar_codes/edit.html.erb
<h1>Editing bar_code</h1>

<%= render 'form' %>

<%= link_to 'Show', @bar_code %> |
<%= link_to 'Back', bar_codes_path %>

app/views/bar_codes/index.html.erb
<h1>Listing bar_codes</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Path</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bar_codes.each do |bar_code| %>
      <tr>
        <td><%= bar_code.code %></td>
        <td><%= bar_code.path %></td>
        <td><%= link_to 'Show', bar_code %></td>
        <td><%= link_to 'Edit', edit_bar_code_path(bar_code) %></td>
        <td><%= link_to 'Destroy', bar_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bar code', new_bar_code_path %>

app/views/bar_codes/new.html.erb
<h1>New bar_code</h1>

<%= render 'form' %>

<%= link_to 'Back', bar_codes_path %>

app/views/bar_codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @bar_code.code %>
</p>

<p>
  <strong>Path:</strong>
  <%= @bar_code.path %>
</p>

<%= link_to 'Edit', edit_bar_code_path(@bar_code) %> |
<%= link_to 'Back', bar_codes_path %>