config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/Index'

  resources :status_clients

  resources :clients

  resources :bar_codes

  resources :visits

  resources :municipalities

  resources :states

end

app/models/municipality.rb
class Municipality < ActiveRecord::Base
	belongs_to :state
end

app/controllers/municipalities_controller.rb
class MunicipalitiesController < ApplicationController
  before_action :set_municipality, only: [:show, :edit, :update, :destroy]

  # GET /municipalities
  # GET /municipalities.json
  def index
    @municipalities = Municipality.all
  end

  # GET /municipalities/1
  # GET /municipalities/1.json
  def show
  end

  # GET /municipalities/new
  def new
    @municipality = Municipality.new
  end

  # GET /municipalities/1/edit
  def edit
  end

  # POST /municipalities
  # POST /municipalities.json
  def create
    @municipality = Municipality.new(municipality_params)

    respond_to do |format|
      if @municipality.save
        format.html { redirect_to @municipality, notice: 'Municipality was successfully created.' }
        format.json { render :show, status: :created, location: @municipality }
      else
        format.html { render :new }
        format.json { render json: @municipality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /municipalities/1
  # PATCH/PUT /municipalities/1.json
  def update
    respond_to do |format|
      if @municipality.update(municipality_params)
        format.html { redirect_to @municipality, notice: 'Municipality was successfully updated.' }
        format.json { render :show, status: :ok, location: @municipality }
      else
        format.html { render :edit }
        format.json { render json: @municipality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /municipalities/1
  # DELETE /municipalities/1.json
  def destroy
    @municipality.destroy
    respond_to do |format|
      format.html { redirect_to municipalities_url, notice: 'Municipality was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_municipality
      @municipality = Municipality.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def municipality_params
      params.require(:municipality).permit(:name, :stateId)
    end
end

app/helpers/municipalities_helper.rb
module MunicipalitiesHelper
end

app/views/municipalities/_form.html.erb
<%= form_for(@municipality) do |f| %>
  <% if @municipality.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@municipality.errors.count, "error") %> prohibited this municipality from being saved:</h2>

      <ul>
      <% @municipality.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :stateId %><br>
    <%= f.text_field :stateId %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/municipalities/edit.html.erb
<h1>Editing municipality</h1>

<%= render 'form' %>

<%= link_to 'Show', @municipality %> |
<%= link_to 'Back', municipalities_path %>

app/views/municipalities/index.html.erb
<h1>Listing municipalities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Stateid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @municipalities.each do |municipality| %>
      <tr>
        <td><%= municipality.name %></td>
        <td><%= municipality.stateId %></td>
        <td><%= link_to 'Show', municipality %></td>
        <td><%= link_to 'Edit', edit_municipality_path(municipality) %></td>
        <td><%= link_to 'Destroy', municipality, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Municipality', new_municipality_path %>

app/views/municipalities/new.html.erb
<h1>New municipality</h1>

<%= render 'form' %>

<%= link_to 'Back', municipalities_path %>

app/views/municipalities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @municipality.name %>
</p>

<p>
  <strong>Stateid:</strong>
  <%= @municipality.stateId %>
</p>

<%= link_to 'Edit', edit_municipality_path(@municipality) %> |
<%= link_to 'Back', municipalities_path %>